### ISSUE TITLE
head table error

### ISSUE THREAD

**Issue by thlinard** [HinTak/Font-Validator#30] opened 2017-11-20 13:13 UTC
When I try to validate the `head` table of a non-Apple font, I obtain an error:
"Error: Input string was not in a correct format". An XML report (.report.xml) file is generated, but not the HTML one (.report.html). I have no error with the `head` table unchecked.

Tested with many Google fonts like 
https://github.com/JulietaUla/Montserrat/blob/master/fonts/ttf/Montserrat-Regular.ttf

Tested with Calibri Regular (Calibri.ttf), version 6.20 (Windows 10 Fall Creator Update).

Tested with Minion Pro Regular (MinionPro-Regular.otf), version 2.112.

On the contrary, TTF files from Apple (Apple Chancery.ttf, Zapfino.ttf) are fine.

Tested with Mac.OS.X.FontValGUI-Seifert-2.1.1.zip

**Comment by HinTak** [comment] 2018-08-05 05:38
Can you post the actual xml report please? I don't need the font itself but that would be useful too, if the report itself does not shed any light on the issue. If necessary, privately

**Comment by Pomax** [comment] 2018-08-05 16:48
I don't see any errors in the `head` table for the font you linked.
![image](https://user-images.githubusercontent.com/177243/43687971-bdf458ba-9894-11e8-8f41-e70a77e35b3d.png)

**Comment by thlinard** [comment] 2018-08-27 17:08
Sorry for the delay. Here is the .report.xml file (I checked the head table, so no .report.html was generated).
[Montserrat-Regular.ttf.report.xml.zip](https://github.com/HinTak/Font-Validator/files/2324854/Montserrat-Regular.ttf.report.xml.zip)

**Comment by Pomax** [comment] 2018-08-27 23:42
heh. `<Report ErrorType="W" ErrorCode="W0022" Message="Recommended table is missing" Details="kern" />`. Probably something worth turning off @HinTak, given that `kern` is super duper no longer recommended and a terrible idea ever since GPOS got introduced =)

**Comment by Pomax** [comment] 2018-08-27 23:43
@thlinard this report has no errors in it for the `head` table.

**Comment by thlinard** [comment] 2018-08-28 08:59
I didn't say the font has an error in the `head` table. When I try to validate the `head` table of a non-Apple font, I obtain an error (a pop-up window):
"Error: Input string was not in a correct format".

And the process of creating the .report.xml ends, and no .report.html is created.

**Comment by thlinard** [comment] 2018-08-28 09:03
The same report with `head` unchecked (three files created).
[Montserrat-Regular.ttf.report.zip](https://github.com/HinTak/Font-Validator/files/2327304/Montserrat-Regular.ttf.report.zip)

**Comment by HinTak** [comment] 2018-08-28 16:59
Sorry I haven't looked at the first posted report yet, but if it is truncated, then the failed table is perhaps alphabetically a few ones after 'head', including rasterization test. Anyway, I'll have a look soon. Meanwhile, if you could try switching off rasterization test and/off all the ones after 'h' may be an idea.

**Comment by thlinard** [comment] 2018-08-28 17:07
I tried switching off after `head`: same error message, same truncated .report.xml, and no .report.html. The rasterization test isn't available (grayed out).
[Montserrat-Regular.ttf.report.xml.version2.zip](https://github.com/HinTak/Font-Validator/files/2329079/Montserrat-Regular.ttf.report.xml.version2.zip)

**Comment by HinTak** [comment] 2020-04-06 12:21
@thlinard I see you are French and so likely have your computer in a non-English locale - do you think it might be the same as https://github.com/HinTak/Font-Validator/issues/52 (affecting Russian and Turkish? users). Anyway the current https://github.com/JulietaUla/Montserrat/blob/master/fonts/ttf/Montserrat-Regular.ttf is about a year younger, and I don't have problem processing it. I am inclined to close this as same as #52 which I am going to look at now.

**Comment by HinTak** [comment] 2020-04-06 12:27
Yes, I can reproduce the problem by setting my language setting to french.

**Comment by HinTak** [comment] 2020-04-06 13:07
Fixed non-English locale issue in https://github.com/HinTak/Font-Validator/commit/46cd98a6b18d7f4e3aa7b9aac3e316285c34577a

**Closed by HinTak** 2020-04-06 13:07 UTC

**Comment by thlinard** [comment] 2020-04-08 08:55
Thank you!
